# Generated by Django 4.0 on 2022-01-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='AAAA'),
        ),
    ]
